# Generated by Django 4.2.5 on 2023-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('count', models.TextField(blank=True, null=True)),
                ('wordcount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
